### ISSUE TITLE
Entangled comes with Redis?

### ISSUE THREAD

**Issue by alereisan** [dchacke/entangled#234]
The readme says (at least for my understanding) that Redis is included in Entangled. But if I run ```$ redis-server``` I get: "zsh: command not found: redis-server" - do I need to install redis-server manually?

**Comment by dchacke** [comment]
It comes with a [Ruby client for Redis](https://rubygems.org/gems/redis/versions/3.2.1), but not with [Redis itself](http://redis.io/). You will have to [install](http://redis.io/download) Redis manually, and then Entangled will automatically know how to connect to it.

Having said that, I realize that the Readme may not be entirely clear on this. I will update it accordingly. Thanks for pointing me to it.
