### ISSUE TITLE
Can I use entangled  in production? Do you have plans to keep maintaining it ?

### ISSUE THREAD

**Issue by ffabreti** [dchacke/entangled#236]
@dchacke 
     I think this gem is awesome, as it makes really transparent integrating  pubsub cycle into Rails.
     Do you have plans to keep maintaining it ?

**Comment by dchacke** [comment]
Yes, I do plan on maintaining it. My time has been limited so I have mostly addressed issues as opposed to developing new features, but at the end of the day it's all plain old sockets and Redis with some sugar on top, so I don't anticipate too much breaking soon.
